on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: "Setup Miniconda"
        uses: "conda-incubator/setup-miniconda@v2"
        with:
          activate-environment: opt2024
          environment-file: environment.yml

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto
        run: quarto render .

      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
